# -*- coding: utf-8 -*-
"""DATA534_Green_Score_ML_Project_JO

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1US4W0eiieAbWc06l_tpEthJZ0MwJQ9ZI
"""

#import necessary libraries for data manipulation and visualization
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

#import the dataset we recreated for this project using kagglehub
import kagglehub

path = kagglehub.dataset_download("nudratabbas/global-green-energy-pulse-real-time-renewable")

print("Path to dataset files:", path)

globalgreen = pd.read_csv(path + "/global_green_energy_pulse_20260112.csv")

globalgreen.info()

globalgreen.head()

globalgreen.describe()

#use a portion of globalgreen, specifically "city," "latitude," and "longitude"
#in order to merge "city" column into our new dataframe afte performing a new
#API call to OpenMeteo

unique_lat_lon = globalgreen[['city', 'latitude', 'longitude']].drop_duplicates().reset_index(drop=True)
display(unique_lat_lon)

"""Using an API call, I'm going to recreate Nudrat's Green Score dataset using the same ten cities but lengthen the amount of time from a few weeks starting in 2026 to the entire year of 2025. Doing so, we will increase the datasize and be able to examine seasonal changes as well as yearly trend. Using this year is also important in figuring out if each city has the capacity to incorporate renewable energy infrastructure NOW, using the most recent years' data. In addition to the wind speed and shortwave radiation variables, I will also be adding the following variables for further examination-- cloud cover, temperature, and humidity."""

#API call to OpenMeteo for the ten cities in globalgreen, including its current features
#plus the new features we added for uniqueness.

api = "https://archive-api.open-meteo.com/v1/archive?latitude=40.71,35.68,51.5,19.07,-33.86,52.52,-23.55,30.04,6.52,39.9&longitude=-74,139.76,-0.12,72.87,151.2,13.4,-46.63,31.23,3.37,116.4&start_date=2025-01-01&end_date=2025-12-31&hourly=temperature_2m,relative_humidity_2m,cloud_cover,wind_speed_100m,shortwave_radiation"

#read the data which is in JSON formatting
data = pd.read_json(api)

data.head()

#parse data from JSON to pandas DataFrame
all_hourly = []

for index, row in data.iterrows():
    loc_hourly_data = pd.DataFrame(row["hourly"])
    loc_hourly_data["latitude"] = row["latitude"]
    loc_hourly_data["longitude"] = row["longitude"]
    all_hourly.append(loc_hourly_data)

df = pd.concat(all_hourly, ignore_index = True)

df.head()

#latitude and longitude differ in both df and unique_lat_long, so we need to
#ensure formats are the same. we chose integer type as the exact coordinate
#locations are not necessary for the data analysis we will be performing

df["latitude"] = df["latitude"].astype(int)
df["longitude"] = df["longitude"].astype(int)

unique_lat_lon["latitude"] = unique_lat_lon["latitude"].astype(int)
unique_lat_lon["longitude"] = unique_lat_lon["longitude"].astype(int)

df = pd.merge(df, unique_lat_lon, on = ["latitude", "longitude"], how = "left")

#check for nulls to assess whether missing data imputation is necessary
df.isnull().sum()

df

#we will reorder columns in the DataFrame. this step is not essential, but we wanted the dataset to
#appear similar to the original one represented in globalgreen

new_col_order = [
    "time",
    "city",
    "latitude",
    "longitude",
    "shortwave_radiation",
    "wind_speed_100m",
    "temperature_2m",
    "relative_humidity_2m",
    "cloud_cover"
]

df = df[new_col_order]

df.head()

#moving on to recreating the green score feature, which will involve using the
#minimum and maximums for both shortwave radiation and windspeed, stored in these
#local variables.

solar_max = df.shortwave_radiation.max()
solar_min = df.shortwave_radiation.min()

wind_max = df.wind_speed_100m.max()
wind_min = df.wind_speed_100m.min()

"""Important note:

"green_score" is not an official sustainability metric used by any organization. It’s a custom, engineered index created specifically for this dataset to make analysis easier.

In simple terms, it combines solar radiation and wind speed to represent how favorable the conditions are for renewable energy generation at a given hour.

It is a derived feature designed for comparative analysis and machine learning, rather than a real-world certification or rating.
"""

df.loc[:, "green_score"] = ((0.5 * ((df["shortwave_radiation"] - solar_min) / (solar_max - solar_min)))
+ (0.5 * ((df["wind_speed_100m"] - wind_min) / (wind_max - wind_min))))

#normalized_value = (x − min) / (max − min)
#green_score = 0.5 * solar_normalized + 0.5 * wind_normalized
#(the equation we received from Nudrat, upon request, in order to recreate her dataset)

df.head()

df.info()

#initial look into the distribution of green scores
df.green_score.describe()

#describe() function does not show median so we show it here
df.green_score.median()

#in order to manipulate the time feature we will convert to datetime, decompose it into columns,
#and drop the initial time column.
df["time"] = pd.to_datetime(df["time"])
df["year"] = df["time"].dt.year
df["month"] = df["time"].dt.month
df["day"] = df["time"].dt.day
df["hour"] = df["time"].dt.hour

df.drop("time", axis=1, inplace=True)

df.head()

#insights into size of the new dataset
num_rows = len(df)
print(f"Number of rows in the DataFrame: {num_rows}")

num_cols = len(df.columns)
print(f"Numer of columns in the DataFrame: {num_cols}")

datapoints = num_rows * num_cols
print(f"Total number of datapoints in the DataFrame: {datapoints}")

"""VISUALIZATIONS & FURTHER EXPLORATION"""

#isolate correlation variables, leaving out nominal and ordinal features that
#are unneccessary for comparative analysis

corr_vars = df.copy().drop(columns = ["city", "year", "month", "day", "hour"])

sns.heatmap(corr_vars.corr(), annot = True, cmap = "coolwarm")
plt.show()

#plot the distribution of green scores
plt.figure(figsize = (10, 6))
sns.histplot(df["green_score"], kde = True)

median_green_score = df["green_score"].median()
mean_green_score = df["green_score"].mean()

plt.axvline(median_green_score, color = "red", linestyle = "--", label = f"Median: {median_green_score:.2f}")

plt.axvline(mean_green_score, color = "green", linestyle = "-", label = f"Mean: {mean_green_score:.2f}")

plt.title("Overall Distribution of Green Scores for All Ten Cities")
plt.xlabel("Green Score")
plt.ylabel("Frequency")
plt.legend()
plt.show()

#separate green scores between Northern and Southern hemisphere cities
#in order to account for distinct seasonalities

northern_hemisphere = df[df["latitude"] >= 0]
southern_hemisphere = df[df["latitude"] < 0]

#show distribution of green scores for both in side-by-side  subplots

northern_median_green_score = northern_hemisphere["green_score"].median()
northern_mean_green_score = northern_hemisphere["green_score"].mean()

southern_median_green_score = southern_hemisphere["green_score"].median()
southern_mean_green_score = southern_hemisphere["green_score"].mean()

fig, axs = plt.subplots(1, 2, figsize=(24, 9))

sns.histplot(northern_hemisphere["green_score"], kde = True, ax = axs[0])
axs[0].axvline(northern_median_green_score, color = "red", linestyle = "--", label = f"Median: {northern_median_green_score:.2f}")
axs[0].axvline(northern_mean_green_score, color = "green", linestyle = "--", label = f"Mean: {northern_mean_green_score:.2f}")
axs[0].set_title("Distribution of Green Score for Northern Hemisphere Cities")
axs[0].set_xlabel("Green Score")
axs[0].set_ylabel("Frequency")
axs[0].legend()

sns.histplot(southern_hemisphere["green_score"], kde = True, ax = axs[1])
axs[1].set_title("Distribution of Green Score for Southern Hemisphere Cities")
axs[1].axvline(southern_median_green_score, color = "red", linestyle = "--", label = f"Median: {southern_median_green_score:.2f}")
axs[1].axvline(southern_mean_green_score, color = "green", linestyle = "--", label = f"Mean: {southern_mean_green_score:.2f}")
axs[1].set_title("Distribution of Green Score for Southern Hemisphere Cities")
axs[1].set_xlabel("Green Score")
axs[1].set_ylabel("Frequency")
axs[1].legend()

plt.tight_layout()
plt.show()

df.green_score.describe()

fig, axes = plt.subplots(1, 2, figsize=(16, 6))

#visualize relationship between green score and shortwave radiation
sns.scatterplot(x = "shortwave_radiation", y = "green_score", data = df, ax = axes[0])
axes[0].set_title("Green Score vs. Shortwave Radiation")
axes[0].set_xlabel("Shortwave Radiation")
axes[0].set_ylabel("Green Score")

#visualize relationship between green score and wind speed
sns.scatterplot(x = "wind_speed_100m", y = "green_score", data = df, ax = axes[1])
axes[1].set_title("Green Score vs. Wind Speed")
axes[1].set_xlabel("Wind Speed (m/s)")
axes[1].set_ylabel("Green Score")

plt.tight_layout()
plt.show()

#visualize average hourly temperature and average hourly shortave radiation
hourly_temp = df.groupby("hour")[["temperature_2m"]].mean()
hourly_shortwave = df.groupby("hour")[["shortwave_radiation"]].mean()

fig, axes = plt.subplots(1, 2, figsize = (16, 6))

sns.lineplot(hourly_temp, ax = axes[0])
axes[0].set_title("Average Hourly Temperature")
axes[0].set_xlabel("Hour")
axes[0].set_ylabel("Temperature")
axes[0].grid(True)

sns.lineplot(hourly_shortwave, ax = axes[1])
axes[1].set_title("Average Hourly Shortwave Radiation")
axes[1].set_xlabel("Hour")
axes[1].set_ylabel("Shortwave Radiation")
axes[1].grid(True)

plt.tight_layout()
plt.show()

#visualize other average hourly variables: cloud cover and relative humidity
hourly_cc = df.groupby("hour")[["cloud_cover"]].mean()
hourly_rh = df.groupby("hour")[["relative_humidity_2m"]].mean()

fig, axes = plt.subplots(1, 2, figsize = (16, 6))

sns.lineplot(hourly_cc, ax = axes[0])
axes[0].set_title("Average Hourly Cloud Cover")
axes[0].set_xlabel("Hour")
axes[0].set_ylabel("Cloud Cover")
axes[0].grid(True)

sns.lineplot(hourly_rh, ax = axes[1])
axes[1].set_title("Average Hourly Relative Humidity")
axes[1].set_xlabel("Hour")
axes[1].set_ylabel("Relative Humidity")
axes[1].grid(True)

plt.tight_layout()
plt.show()

#visualize average monthly variables: green score, shortwave radiation, and wind speed
monthly_avg  =  df.groupby("month")[["green_score", "shortwave_radiation", "wind_speed_100m"]].mean().reset_index()

fig, axes = plt.subplots(1, 3, figsize=(20, 6))

sns.lineplot(x = "month", y = "green_score", data = monthly_avg, ax = axes[0])
axes[0].set_title("Average Monthly Green Score")
axes[0].set_xlabel("Month")
axes[0].set_ylabel("Green Score")
axes[0].grid(True)

sns.lineplot(x = "month", y = "shortwave_radiation", data = monthly_avg, ax = axes[1])
axes[1].set_title("Average Monthly Shortwave Radiation")
axes[1].set_xlabel("Month")
axes[1].set_ylabel("Shortwave Radiation")
axes[1].grid(True)

sns.lineplot(x = "month", y = "wind_speed_100m", data = monthly_avg, ax = axes[2])
axes[2].set_title("Average Monthly Wind Speed")
axes[2].set_xlabel("Month")
axes[2].set_ylabel("Wind Speed (m/s)")
axes[2].grid(True)

plt.tight_layout()
plt.show()

"""Looking at average monthly data:

- Green Scores higher in spring/summer months and lower in fall/winter.
- Shortwave radiation high in all months except for Jan/Feb and Oct-Dec.
- With wind speed, trend appears to show a somewhat seasonal oscillation, but contains much more variability.
"""

#isolate average green score per city
avgcity_green = df.groupby(["city"])[["green_score"]].mean().sort_values(by = "green_score", ascending = False).reset_index()
avgcity_green

"""These are the cities with the highest average green scores."""

#visualize using a bar plot
plt.figure(figsize = (6, 4))
sns.barplot(x = "green_score", y = "city", data = avgcity_green)

plt.title("Average Green Scores by City")
plt.xlabel("Green Score")
plt.ylabel("City")
plt.xticks(rotation = 45, ha = "right")
plt.tight_layout()
plt.grid(axis = "x")
plt.show()

"""Based on my analysis:
  - Features to keep:
    - relative humidity based on the negative correlation to green score.
  - Features to exclude:
    - exclude cloud cover due to weak correlation, because it contains very little predictive power. Including it might introduce noise.
    - exclude temperature due to multicollinearity with solar radiation and low correlation to green score.
"""

df.head()

"""To prepare for machine learning, we need to convert city labels to boolean values and drop the original column."""

df = pd.get_dummies(df, columns=['city'], drop_first=False)
df.head()

"""MACHINE LEARNING:

I will train a Decision Tree Regressor, Linear Regression, and RandomForestRegressor model without dropping any columns first.

I will perform 80/20 train/test split for each as well as 5-fold cross-validation.
"""

#import sci-kit learn for machine learning
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler

"""Decision Tree Regressor:"""

#make a copy to ensure data integrity
df2 = df.copy()

#define X and y for the first model training (before dropping columns)
X = df2.drop(columns = ["green_score"])
y = df2["green_score"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

#convert back to dataframes
X_train_scaled_df = pd.DataFrame(X_train_scaled, columns = X_train.columns, index = X_train.index)
X_test_scaled_df = pd.DataFrame(X_test_scaled, columns = X_test.columns, index = X_test.index)

#initialize and train the Decision Tree Regressor
dt_regressor = DecisionTreeRegressor(random_state = 42)
dt_regressor.fit(X_train_scaled_df, y_train)

#make predictions on the scaled test set
y_pred_dt = dt_regressor.predict(X_test_scaled_df)

#evaluate the model
mae_dt = mean_absolute_error(y_test, y_pred_dt)
mse_dt = mean_squared_error(y_test, y_pred_dt)
rmse_dt = np.sqrt(mse_dt)
r2_dt = r2_score(y_test, y_pred_dt)

print(f"Decision Tree Regressor Performance:")
print(f"Mean Absolute Error (MAE): {mae_dt:.4f}")
print(f"Mean Squared Error (MSE): {mse_dt:.4f}")
print(f"Root Mean Squared Error (RMSE): {rmse_dt:.4f}")
print(f"R-squared (R2): {r2_dt:.4f}")

#import cross-validation from sci-kit learn
from sklearn.model_selection import KFold, cross_val_score

#define cross validation
kf = KFold(n_splits = 5, shuffle = True, random_state = 42)

#scale dataset X for cross-validation
scaler_full = StandardScaler()
X_scaled_full = scaler_full.fit_transform(X)
X_scaled_full_df = pd.DataFrame(X_scaled_full, columns = X.columns, index = X.index)

#perform cross-validation
cv_scores_dt = cross_val_score(dt_regressor, X_scaled_full_df, y, cv = kf,
                            scoring = "r2", n_jobs = -1)

print(f"Cross-validation R^2 scores for Decision Tree: {cv_scores_dt}")
print(f"Mean cross-validation R^2 for Decision Tree: {np.mean(cv_scores_dt):.4f}")
print(f"Standard deviation of cross-validation R^2 for Decision Tree: {np.std(cv_scores_dt):.4f}")

dt_feature_importances = pd.Series(dt_regressor.feature_importances_, index = X_train.columns)

plt.figure(figsize=(6, 4))
sns.barplot(x = dt_feature_importances, y = dt_feature_importances.index)
plt.title("Feature Importances (Decision Tree)")
plt.xlabel("Importance")
plt.ylabel("Feature")
plt.show()

"""Repeat but drop columns:"""

df3 = df.copy()

#define X and y, then drop "green_score", "temperature_2m", and "cloud_cover"
X_dt_dropped = df3.drop(columns = ["green_score", "temperature_2m", "cloud_cover"])
y_dt_dropped = df3["green_score"]

X_train_dt_dropped, X_test_dt_dropped, y_train_dt_dropped, y_test_dt_dropped = train_test_split(X_dt_dropped, y_dt_dropped,
                                                                                                test_size = 0.2, random_state = 42)

scaler_dt_dropped = StandardScaler()
X_train_scaled_dt_dropped = scaler_dt_dropped.fit_transform(X_train_dt_dropped)
X_test_scaled_dt_dropped = scaler_dt_dropped.transform(X_test_dt_dropped)

#convert back to dataframes
X_train_scaled_df_dt_dropped = pd.DataFrame(X_train_scaled_dt_dropped, columns = X_train_dt_dropped.columns, index = X_train_dt_dropped.index)
X_test_scaled_df_dt_dropped = pd.DataFrame(X_test_scaled_dt_dropped, columns = X_test_dt_dropped.columns, index = X_test_dt_dropped.index)

#initialize and train the Decision Tree Regressor
dt_regressor_dropped = DecisionTreeRegressor(random_state = 42)
dt_regressor_dropped.fit(X_train_scaled_df_dt_dropped, y_train_dt_dropped)

#make predictions on the scaled test set
y_pred_dt_dropped = dt_regressor_dropped.predict(X_test_scaled_df_dt_dropped)

#evaluate the model
mae_dt_dropped = mean_absolute_error(y_test_dt_dropped, y_pred_dt_dropped)
mse_dt_dropped = mean_squared_error(y_test_dt_dropped, y_pred_dt_dropped)
rmse_dt_dropped = np.sqrt(mse_dt_dropped)
r2_dt_dropped = r2_score(y_test_dt_dropped, y_pred_dt_dropped)

print("Decision Tree Regressor Model Performance:")
print(f"Mean Absolute Error (MAE): {mae_dt_dropped:.4f}")
print(f"Mean Squared Error (MSE): {mse_dt_dropped:.4f}")
print(f"Root Mean Squared Error (RMSE): {rmse_dt_dropped:.4f}")
print(f"R-squared (R2): {r2_dt_dropped:.4f}")

#perform cross-validation
scaler_full_dt_dropped = StandardScaler()
X_scaled_full_dt_dropped = scaler_full_dt_dropped.fit_transform(X_dt_dropped)
X_scaled_full_df_dt_dropped = pd.DataFrame(X_scaled_full_dt_dropped, columns = X_dt_dropped.columns, index = X_dt_dropped.index)

cv_scores_dt_dropped = cross_val_score(dt_regressor_dropped, X_scaled_full_df_dt_dropped, y_dt_dropped, cv = kf, scoring = "r2", n_jobs = -1)

print()
print(f"Cross-validation R^2 scores for Decision Tree (dropped features): {cv_scores_dt_dropped}")
print(f"Mean cross-validation R^2 for Decision Tree (dropped features): {np.mean(cv_scores_dt_dropped):.4f}")
print(f"Standard deviation of cross-validation R^2 for Decision Tree (dropped features): {np.std(cv_scores_dt_dropped):.4f}")

"""Continue training/testing with dropped columns, as shown by decrease in error.

Linear Regression:
"""

df4 = df.copy()

#define X and y, dropping columns
X_lr = df4.drop(columns = ["green_score", "temperature_2m", "cloud_cover"])
y_lr = df4["green_score"]

X_train_lr, X_test_lr, y_train_lr, y_test_lr = train_test_split(X_lr, y_lr, test_size = 0.2, random_state = 42)

#initialize and fit a new scaler for the feature-selected data
scaler = StandardScaler()
X_train_scaled_lr = scaler.fit_transform(X_train_lr)
X_test_scaled_lr = scaler.transform(X_test_lr)

#convert back to dataframes
X_train_scaled_df_lr = pd.DataFrame(X_train_scaled_lr, columns = X_train_lr.columns, index = X_train_lr.index)
X_test_scaled_df_lr = pd.DataFrame(X_test_scaled_lr, columns = X_test_lr.columns, index = X_test_lr.index)

#initialize and train Linear Regression
lr_regressor = LinearRegression()
lr_regressor.fit(X_train_scaled_df_lr, y_train_lr)

#make predictions on the scaled test set
y_pred_lr = lr_regressor.predict(X_test_scaled_df_lr)

#evaluate the model
mae_lr = mean_absolute_error(y_test_lr, y_pred_lr)
mse_lr = mean_squared_error(y_test_lr, y_pred_lr)
rmse_lr = np.sqrt(mse_lr)
r2_lr = r2_score(y_test_lr, y_pred_lr)

print(f"Linear Regression Model Performance:")
print(f"Mean Absolute Error (MAE): {mae_lr:.4f}")
print(f"Mean Squared Error (MSE): {mse_lr:.4f}")
print(f"Root Mean Squared Error (RMSE): {rmse_lr:.4f}")
print(f"R-squared (R2): {r2_lr:.4f}")

#cross-validation for Linear Regression
cv_scores_lr = cross_val_score(lr_regressor, X_scaled_full_df, y, cv = kf,
                            scoring = "r2", n_jobs = -1)

print(f"Cross-validation R^2 scores for Linear Regression: {cv_scores_lr}")
print(f"Mean cross-validation R^2 for Linear Regression: {np.mean(cv_scores_lr):.4f}")
print(f"Standard deviation of cross-validation R^2 for Linear Regression: {np.std(cv_scores_lr):.4f}")

"""Random Forest Regressor:"""

df5 = df.copy()

X = df5.drop(columns = ["green_score", "temperature_2m", "cloud_cover"])
y = df5["green_score"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

#convert back to dataframes
X_train_scaled_df = pd.DataFrame(X_train_scaled, columns = X_train.columns, index = X_train.index)
X_test_scaled_df = pd.DataFrame(X_test_scaled, columns = X_test.columns, index = X_test.index)

#initialize Random Forest regressor
rf_regressor = RandomForestRegressor(n_estimators = 50, random_state = 42, n_jobs = -1)
rf_regressor.fit(X_train_scaled_df, y_train)

y_pred = rf_regressor.predict(X_test_scaled_df)

#evaluate
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("Random Forest Regressor Model Performance:")
print(f"Mean Absolute Error (MAE): {mae:.4f}")
print(f"Mean Squared Error (MSE): {mse:.4f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.4f}")
print(f"R-squared (R2): {r2:.4f}")

#cross-validation for Random Forest
scaler_full = StandardScaler()
X_scaled_full = scaler_full.fit_transform(X)
X_scaled_full_df = pd.DataFrame(X_scaled_full, columns = X.columns, index = X.index)

#define the KFold cross-validation
kf = KFold(n_splits = 5, shuffle = True, random_state = 42)

#perform cross-validation
cv_scores = cross_val_score(rf_regressor, X_scaled_full_df, y, cv = kf,
                            scoring = "r2", n_jobs = -1)

print(f"Random Forest Cross-validation R^2 scores: {cv_scores}")
print(f"Mean cross-validation R^2: {np.mean(cv_scores):.4f}")
print(f"Standard deviation of cross-validation R^2: {np.std(cv_scores):.4f}")

feature_importances = pd.Series(rf_regressor.feature_importances_, index = X_train.columns)

plt.figure(figsize = (6, 4))
sns.barplot(x = feature_importances, y = feature_importances.index)
plt.title("Feature Importances (Random Forest)")
plt.xlabel("Importance")
plt.ylabel("Feature")
plt.show()

#display all scores for all models, after dropping columns
all_model_scores = pd.DataFrame({
    "Model": [
        "Decision Tree Regressor",
        "Linear Regression",
        "Random Forest Regressor"
    ],
    "MAE": [mae_dt_dropped, mae_lr, mae],
    "MSE": [mse_dt_dropped, mse_lr, mse],
    "RMSE": [rmse_dt_dropped, rmse_lr, rmse],
    "R2 Score": [r2_dt_dropped, r2_lr, r2],
    "Cross-Validation R2 Score": [
        np.mean(cv_scores_dt_dropped),
        np.mean(cv_scores_lr),
        np.mean(cv_scores)
    ]
})

#format floating point columns to four decimal places
formatted_scores = all_model_scores.style.format({
    'MAE': '{:.4f}',
    'MSE': '{:.4f}',
    'RMSE': '{:.4f}',
    'R2 Score': '{:.4f}',
    'Cross-Validation R2 Score': '{:.4f}'
})

display(formatted_scores)

"""MODEL APPLICATION:

Next step: Obtain hourly weather data from Charleston SC from 2025 with another API call and use trained model to predict green scores using environmental features. Follow same initial data preparation steps.  
"""

api2 = "https://archive-api.open-meteo.com/v1/archive?latitude=32.78&longitude=-79.93&start_date=2025-01-01&end_date=2025-12-31&hourly=temperature_2m,relative_humidity_2m,cloud_cover,wind_speed_100m,shortwave_radiation"

data2 = pd.read_json(api2)

data2.head()

hourly_data_dict = {}
for index, value in data2["hourly"].items():
    hourly_data_dict[index] = value

df_chs = pd.DataFrame(hourly_data_dict)

df_chs["latitude"] = data2["latitude"].iloc[0].astype(int)
df_chs["longitude"] = data2["longitude"].iloc[0].astype(int)

df_chs.head()

df_chs["time"] = pd.to_datetime(df_chs["time"])
df_chs["year"] = df_chs["time"].dt.year
df_chs["month"] = df_chs["time"].dt.month
df_chs["day"] = df_chs["time"].dt.day
df_chs["hour"] = df_chs["time"].dt.hour

df_chs.drop("time", axis = 1, inplace = True)

df_chs["city_Charleston"] = True

df_chs.head()

#new column ordering dropping unnecessary columns for modeling
new_col_order = ["latitude",
                 "longitude",
                 "shortwave_radiation",
                 "wind_speed_100m",
                 "relative_humidity_2m",
                 "year",
                 "month",
                 "day",
                 "hour",
                 "city_Charleston"]

df_chs = df_chs[new_col_order]
df_chs.head()

df_chs.isnull().sum()

#get the list of columns from the training data X
training_columns = X.columns

#drop the 'city_Charleston' column as it was not in the training data
df_chs = df_chs.drop(columns = ['city_Charleston'])

#add missing city columns and set them to False
for col in training_columns:
    if col.startswith('city_') and col not in df_chs.columns:
        df_chs[col] = False

#make sure order of columns matches the training data
df_chs = df_chs[training_columns]

#scale the new data
df_chs_scaled = scaler.transform(df_chs)

#convert scaled array back to dataframe for prediction
df_chs_scaled_df = pd.DataFrame(df_chs_scaled, columns = training_columns, index = df_chs.index)

#predict using the trained model
chs_predict = lr_regressor.predict(df_chs_scaled_df)

#add predictions to the original df_chs dataframe for easier analysis
df_chs["green_score_pred"] = chs_predict

df_chs.head()

print(df2["green_score"].describe())

print(df_chs["green_score_pred"].describe())

#visualize predicted green scores for Chs
plt.figure(figsize = (10, 6))
sns.histplot(df_chs["green_score_pred"], kde = True)

median_green_score_chs = df_chs["green_score_pred"].median()
mean_green_score_chs = df_chs["green_score_pred"].mean()

plt.axvline(median_green_score, color = "red", linestyle = "--", label = f"Median: {median_green_score_chs:.2f}")
plt.axvline(mean_green_score, color = "green", linestyle = "-", label = f"Average: {mean_green_score_chs:.2f}")

plt.title("Distribution of Predicted Green Scores for Charleston")
plt.xlabel("Predicted Green Score")
plt.ylabel("Frequency")
plt.legend()
plt.show()

df_chs.green_score_pred.describe()

#visualize how Charleston's shortwave radiation and wind speed
#move through the year to observe insights into the predicted
#scores

daily_avg_chs = df_chs.groupby(["year", "month", "day"]).agg({
    "shortwave_radiation": "mean",
    "wind_speed_100m": "mean"
}).reset_index()

daily_avg_chs["date"] = pd.to_datetime(daily_avg_chs[["year", "month", "day"]])

fig, axes = plt.subplots(2, 1, figsize = (8, 6), sharex = True)

sns.lineplot(x = "date", y = "shortwave_radiation", data = daily_avg_chs, ax = axes[0])
axes[0].set_title("Daily Average Shortwave Radiation in Charleston (2025)")
axes[0].set_xlabel("Date")
axes[0].set_ylabel("Shortwave Radiation")
axes[0].grid(True)

sns.lineplot(x = "date", y = "wind_speed_100m", data = daily_avg_chs, ax = axes[1])
axes[1].set_title("Daily Average Wind Speed in Charleston (2025)")
axes[1].set_xlabel("Date")
axes[1].set_ylabel("Wind Speed (m/s)")
axes[1].grid(True)

plt.tight_layout()
plt.show()

"""Based on the linear regression model's performance, we were able to predict green scores for Charleston using data from the year 2025. The average of the predicted green score is notably higher than some of the cities we analyzed suggesting that Charleston presents favorable conditions for renewable energy generation, and has the capacity for both wind and solar energy applications."""